# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Dependency Review

on:
  workflow_dispatch:

  push:
    branches:
      - next

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v3.5.2

      - name: 🚀 Dependency Review
        uses: actions/dependency-review-action@v3.0.6
