# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Special Containers

on:
  workflow_dispatch:

  push:
    paths:
      - 'cloud/container/**'
      - '.github/workflows/publish-container.yml'
    tags:
      - 'v*.*.*'
    branches:
      - next

  pull_request:
    paths:
      - 'cloud/container/**'
      - '.github/workflows/publish-container.yml'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: github.repository_owner == 'AliMD'

    name: Build & Publish Containers
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: alpine
            path: cloud/container/alpine
            description: A minimal Docker image based on Alpine Linux with a complete package index and only 5 MB in size!
            version:
              short: 3
              full: 3.16

          - image: nginx
            path: cloud/container/nginx
            description: High performance, optimized NGINX for server web applications and api proxy with fast cache.
            version:
              short: 1
              full: 1.2.0-1.24-alpine

          # - image: tdlib
          #   path: cloud/container/tdlib
          #   description: Cross-platform library for building Telegram clients.
          #   version:
          #     short: 1
          #     full: 1.8

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v3.5.0

      - name: 🏗 Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          images: |
            name=${{env.REGISTRY}}/alwatr/${{matrix.image}},enable=false
            name=${{env.REGISTRY}}/${{github.repository_owner}}/${{matrix.image}},enable=true

          labels: |
            org.opencontainers.image.authors=Ali.Mihandoost@gmail.com
            org.opencontainers.image.title=@Alwatr/${{matrix.image}}
            org.opencontainers.image.description=${{matrix.description}}

          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{matrix.version.short}}
            type=raw,value=${{matrix.version.full}}
            # type=semver,pattern={{version}},prefix=alwatr-
            # type=semver,pattern={{major}}.{{minor}},prefix=alwatr-

      - name: 🏗 Install cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v3.0.1

      - name: 🏗 Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: 🏗 Log into registry ${{env.REGISTRY}}
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 🚀 Build and push container image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ${{matrix.path}}
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🏗 Sign the published container image
        if: ${{github.event_name != 'pull_request'}}
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: echo "${{steps.meta.outputs.tags}}" | xargs -I {} cosign sign --yes {}@${{steps.build-and-push.outputs.digest}}
